# Generated by Django 4.2.4 on 2024-07-30 19:58

from django.db import migrations, models
import django.db.models.deletion
import django_tidb.fields.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_title', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField()),
                ('playlist', models.BooleanField(blank=True, default=False, null=True)),
                ('last_conversation_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('training', 'training'), ('trained', 'trained'), ('failed', 'failed')], max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='timestamp_search.chat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_stamp', models.CharField(max_length=1000)),
                ('embedding', django_tidb.fields.vector.VectorField(db_comment='hnsw(distance=cosine)', dimensions=800)),
                ('text', models.TextField()),
                ('chunk_index', models.IntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_stamps', to='timestamp_search.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=1000)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prompts', to='timestamp_search.chat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
