# Generated by Django 4.2.4 on 2024-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp_search', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
